name: CI Pipeline - Complaint Analysis

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: ⬇️ Checkout repository
      uses: actions/checkout@v3

    - name: 🐍 Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: 📦 Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: 🔍 Lint with flake8
      run: |
        flake8 scripts --max-line-length=120 --ignore=E203,W503

    - name: ✅ Run tests
      run: |
        pytest tests || echo "No tests found or failed"

    - name: ✅ Finished
      run: echo "✅ CI pipeline completed!"
